service: AtrisServer

functions:
  CreateUser:
    handler: atris_server.create_user
    events:
      - http:
          path: /create_user
          method: post
  AuthenticateUser:
    handler: atris_server.authenticate_user
    events:
      - http:
          path: /authenticate_user
          method: post