[package]
name = "atris_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version="1.0.145", features=["derive"]}
chacha20poly1305 = "0.10.1"
serde_bytes = "0.11.7"
bincode = "1.3.3"
